#cloud-config
packages:
  - curl
hostname: ${hostname}
ssh_pwauth: true
chpasswd:
  expire: false
users:
  - name: cluster
    groups: sudo
    ssh_authorized_keys:
      - ${public_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
write_files:
  - content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    path: /etc/sysctl.d/k8s.conf
runcmd:
  - sudo sysctl --system
  - sudo ip link property add dev eth0 altname public
